#ifndef GB_Z80_ASM_ERROR_HANDLER_H
#define GB_Z80_ASM_ERROR_HANDLER_H

typedef enum ErrorCodes
{
    GBASM_CODE_OK,
    GBASM_ERR_MALFORMED_LINE,
    GBASM_ERR_DUPLICATE_MAIN,
    GBASM_ERR_MAIN_BANK_UNREACHABLE,
    GBASM_CODE_ERROR
} ErrorCode;

#endif //GB_Z80_ASM_ERROR_HANDLER_H
